(()=> {
  const current='a';
  const landscape=`<div class="orvia-landscape"><div class="orvia-landscape__inner"><span class="orvia-landscape__label">ORVIA LANDSCAPE</span><nav class="orvia-landscape__nav" aria-label="ORVIA landscape"><a class="o" href="https://orvia.org.uk/">Oversight</a><a class="r" href="https://orviavoice.co.uk/"${current==='r'?' aria-current="page"':''}>Voice</a><a class="v" href="https://threshold.orvia.org.uk/"${current==='v'?' aria-current="page"':''}>Threshold</a><a class="i" href="https://mia.orvia.org.uk/"${current==='i'?' aria-current="page"':''}>MIA</a><a class="a" href="https://web.orvia.org.uk/"${current==='a'?' aria-current="page"':''}>Web</a></nav></div></div>`;
  const contact=`<div class="orvia-contactbar"><div class="orvia-contactbar__inner"><a href="mailto:hello@orvia.org.uk">hello@orvia.org.uk</a><a href="tel:03300433703">0330 043 3703</a><span class="push">ORVIA Oversight Ltd · Human first. Evidence before assumption.</span></div></div>`;
  const masthead=`<header class="orvia-family-header"><div class="orvia-family-header__inner"><a class="orvia-family-header__brand" href="https://orvia.org.uk/"><img src="https://orvia.org.uk/assets/orvia-logo.png" alt="ORVIA Oversight"><span class="orvia-family-header__product"><strong>WEB</strong><small>Websites · Apps · Voice · Automation</small></span></a><nav class="orvia-family-header__nav" aria-label="WEB navigation"><a href="https://web.orvia.org.uk/#how-it-works">How it works</a><a href="https://web.orvia.org.uk/#pricing">Pricing</a><a href="https://web.orvia.org.uk/#showcase">Live demos</a><a href="https://web.orvia.org.uk/trust/">Trust</a><a href="https://web.orvia.org.uk/#connected">Connected services</a></nav><a class="orvia-family-header__cta" href="https://web.orvia.org.uk/#contact">Start my website</a></div></header>`;
  const footer=`<footer class="orvia-common-footer"><div class="orvia-common-footer__inner"><div class="orvia-common-footer__brand"><a href="https://orvia.org.uk/"><img src="https://orvia.org.uk/assets/orvia-logo.png" alt="ORVIA Oversight"></a><p>One ORVIA landscape. Different services, one evidence-led standard.</p></div><div><h4>ORVIA Landscape</h4><a href="https://orvia.org.uk/">Oversight</a><a href="https://orviavoice.co.uk/">Voice</a><a href="https://threshold.orvia.org.uk/">Threshold</a><a href="https://mia.orvia.org.uk/">MIA</a><a href="https://web.orvia.org.uk/">Web</a></div><div><h4>Contact</h4><a href="tel:03300433703">0330 043 3703</a><a href="mailto:hello@orvia.org.uk">hello@orvia.org.uk</a><a href="https://orvia.org.uk/contact">Contact ORVIA</a><a href="https://orvia.org.uk/privacy">Privacy</a><a href="https://orvia.org.uk/accessibility">Accessibility</a></div></div><div class="orvia-common-footer__base"><span>ORVIA Oversight Ltd · Company No. 16123685 · ICO ZC152311</span><span class="push">Armed Forces Covenant · ERS Bronze</span></div></footer>`;
  if(!document.querySelector('.orvia-contactbar')) document.body.insertAdjacentHTML('afterbegin',contact);
  if(!document.querySelector('.orvia-landscape')) document.querySelector('.orvia-contactbar')?.insertAdjacentHTML('afterend',landscape);
  const existingHeader=document.querySelector('header:not(.orvia-family-header)');
  if(existingHeader) existingHeader.outerHTML=masthead; else if(!document.querySelector('.orvia-family-header')) document.querySelector('.orvia-landscape')?.insertAdjacentHTML('afterend',masthead);
  const oldFooter=document.querySelector('footer:not(.orvia-common-footer)');
  if(oldFooter) oldFooter.outerHTML=footer; else if(!document.querySelector('.orvia-common-footer')) document.body.insertAdjacentHTML('beforeend',footer);
})();