const menu=document.querySelector('.menu-toggle');const nav=document.querySelector('.nav');menu?.addEventListener('click',()=>{const open=nav.classList.toggle('mobile-open');menu.setAttribute('aria-expanded',String(open))});

const form=document.getElementById('enquiry-form');const status=document.getElementById('form-status');const started=document.getElementById('started-at');if(started)started.value=String(Date.now());
form?.addEventListener('submit',async e=>{e.preventDefault();if(!form.reportValidity())return;const button=form.querySelector('button[type="submit"]');button.disabled=true;button.textContent='Sending…';if(status)status.textContent='Sending your enquiry…';const data=Object.fromEntries(new FormData(form).entries());const params=new URLSearchParams(location.search);for(const key of ['utm_source','utm_medium','utm_campaign','utm_content','utm_term'])data[key]=params.get(key)||'';data.landing_path=location.pathname;try{const res=await fetch('https://qokkyynptzeuuebykmbo.supabase.co/functions/v1/web-lead',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const out=await res.json().catch(()=>({}));if(!res.ok)throw new Error(out.error||'Unable to send');form.reset();if(started)started.value=String(Date.now());if(status)status.innerHTML='<strong>Thank you.</strong> Your enquiry has been received. We will respond using the details you provided.'}catch(err){if(status)status.innerHTML='We could not send the form. Please call <a href="tel:03300433703">0330 043 3703</a> or email <a href="mailto:web@orvia.org.uk">web@orvia.org.uk</a>.'}finally{button.disabled=false;button.textContent='Send enquiry'}});

const consentKey='orvia-web-consent-v2';const banner=document.getElementById('cookie-banner');const dialog=document.getElementById('cookie-dialog');const analytics=document.getElementById('consent-analytics');const marketing=document.getElementById('consent-marketing');const tracking={gaId:'',metaPixelId:''};let gaLoaded=false,metaLoaded=false;
function getConsent(){try{return JSON.parse(localStorage.getItem(consentKey))}catch{return null}}
function loadAnalytics(){if(!tracking.gaId||gaLoaded)return;gaLoaded=true;window.dataLayer=window.dataLayer||[];window.gtag=function(){window.dataLayer.push(arguments)};window.gtag('js',new Date());window.gtag('config',tracking.gaId);const s=document.createElement('script');s.async=true;s.src='https://www.googletagmanager.com/gtag/js?id='+encodeURIComponent(tracking.gaId);document.head.append(s)}
function loadMarketing(){if(!tracking.metaPixelId||metaLoaded)return;metaLoaded=true;window.fbq=function(){if(window.fbq.callMethod)window.fbq.callMethod.apply(window.fbq,arguments);else window.fbq.queue.push(arguments)};window.fbq.queue=[];window.fbq.loaded=true;window.fbq.version='2.0';const s=document.createElement('script');s.async=true;s.src='https://connect.facebook.net/en_US/fbevents.js';document.head.append(s);window.fbq('init',tracking.metaPixelId);window.fbq('track','PageView')}
function apply(c){if(!c)return;if(banner)banner.hidden=true;if(c.analytics)loadAnalytics();if(c.marketing)loadMarketing()}
function save(a,m){const c={analytics:!!a,marketing:!!m,recordedAt:new Date().toISOString()};try{localStorage.setItem(consentKey,JSON.stringify(c))}catch{};dialog?.close();apply(c)}
const saved=getConsent();if(saved)apply(saved);else if(banner)banner.hidden=false;
document.getElementById('cookie-reject')?.addEventListener('click',()=>save(false,false));document.getElementById('cookie-accept')?.addEventListener('click',()=>save(true,true));function settings(){const c=getConsent();if(analytics)analytics.checked=!!c?.analytics;if(marketing)marketing.checked=!!c?.marketing;dialog?.showModal()}document.getElementById('cookie-customise')?.addEventListener('click',settings);document.getElementById('cookie-settings-open')?.addEventListener('click',settings);document.getElementById('cookie-save')?.addEventListener('click',()=>save(analytics?.checked,marketing?.checked));